<?php

/**
 * @file
 * Sanbi redirect module.
 */

/**
 * Implements hook_entity_info().
 */
function sanbi_redirect_entity_info() {
  $info['sanbi_redirect'] = array(
    'label' => t('Sanbi Redirect'),
    'base table' => 'sanbi_redirect',
    'entity keys' => array(
      'id' => 'rid',
    ),
    'fieldable' => FALSE,
    'uuid' => FALSE,
  );

  return $info;
}

/**
 * Implements hook_menu().
 */
function sanbi_redirect_menu() {
  $items['admin/config/search/sanbi_redirect'] = array(
    'title' => 'Sanbi redirects',
    'description' => 'Matching pattern redirects to target.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sanbi_redirect_list_form'),
    'access arguments' => array('administer matchredirect'),
    'file' => 'sanbi_redirect.admin.inc',
  );
  $items['admin/config/search/sanbi_redirect/add'] = array(
    'title' => 'Add sanbi redirect',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sanbi_redirect_add_form'),
    'access arguments' => array('administer matchredirect'),
    'file' => 'sanbi_redirect.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/search/sanbi_redirect/edit/%sanbi_redirect'] = array(
    'title' => 'Edit sanbi redirect',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sanbi_redirect_add_form', 5),
    'access arguments' => array('administer matchredirect'),
    'file' => 'sanbi_redirect.admin.inc',
  );
  $items['admin/config/search/sanbi_redirect/delete/%sanbi_redirect'] = array(
    'title' => 'Delete sanbi redirect',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sanbi_redirect_delete_form', 5),
    'access arguments' => array('administer matchredirect'),
    'file' => 'sanbi_redirect.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function sanbi_redirect_permission() {
  $perm['administer matchredirect'] = array(
    'title' => t('Administer Sanbi Redirect'),
  );
  return $perm;
}

/**
 * Implements hook_init().
 */
function sanbi_redirect_init() {
  // Get all redirects.
  $results = sanbi_redirect_load_multiple(array());
  // Alias of page user is on.
  $current_alias = drupal_get_path_alias();

  // Check each redirect for a match and stop if found.
  foreach ($results as $row) {

    $patterns = $row->source_pattern;
    $redirect = $row->target;
    $override = $row->override;
    $code = $row->status_code;
    if (drupal_match_path($current_alias, $patterns)) {

      // JJ : this is a fudge! Catch the following pattern and generate custom redirect
      if ($patterns == 'plant*/*.htm' || $patterns == '*.htm'){

        //Pathinfo
        $parts = pathinfo($current_alias);

        // New redirect
        $redirect = 'plants/' . $parts['filename'];
      }

      // Check if the current page exists unless overridden.
      if ($override || !sanbi_redirect_url_exists()) {
        // Do the redirect.
        drupal_goto($redirect, array(), $code);
        break;
      }
    }
  }
}

/**
 * Checks if current page is registered as a menu item (exists).
 *
 * @return bool
 *   Whether or not the menu item was found.
 */
function sanbi_redirect_url_exists() {
  return (bool) menu_get_item();
}

/**
 * Implements hook_theme().
 */
function sanbi_redirect_theme() {
  return array(
    'sanbi_redirect_list_form' => array(
      'render element' => 'form',
      'file' => 'sanbi_redirect.admin.inc',
    ),
  );
}

/**
 * Saves a redirect.
 *
 * @param object $redirect
 *   The redirect object to be saved.
 *
 * @throws Exception
 */
function sanbi_redirect_save($redirect) {
  $transaction = db_transaction();

  try {
    // Load the stored entity, if any.
    if (!empty($redirect->rid) && !isset($redirect->original)) {
      $redirect->original = entity_load_unchanged('sanbi_redirect', $redirect->rid);
    }

    // Invoke hook_entity_presave() on other modules.
    module_invoke_all('entity_presave', $redirect, 'sanbi_redirect');

    // Save to the database and fire relevent hooks.
    if (!empty($redirect->rid)) {
      drupal_write_record('sanbi_redirect', $redirect, array('rid'));
      // Invoke hook_entity_update() on other modules.
      module_invoke_all('entity_update', $redirect, 'sanbi_redirect');
    }
    else {
      drupal_write_record('sanbi_redirect', $redirect);
      // Invoke hook_entity_insert() on other modules.
      module_invoke_all('entity_insert', $redirect, 'sanbi_redirect');
    }

    unset($redirect->original);
  }
  catch (Exception $e) {
    $transaction->rollback('sanbi_redirect');
    watchdog_exception('sanbi_redirect', $e);
    throw $e;
  }
}

/**
 * Deletes a redirect.
 *
 * @param int $rid
 *   The id of the redirect to be deleted.
 *
 * @throws Exception
 */
function sanbi_redirect_delete($rid) {
  $transaction = db_transaction();
  $redirect = sanbi_redirect_load($rid);
  try {
    // Invoke hook_entity_delete() on other modules.
    module_invoke_all('entity_delete', $redirect, 'sanbi_redirect');

    db_delete('sanbi_redirect')
      ->condition('rid', $rid, '=')
      ->execute();
  }
  catch (Exception $e) {
    $transaction->rollback('sanbi_redirect');
    watchdog_exception('sanbi_redirect', $e);
    throw $e;
  }
}

/**
 * Loads a redirect and returns it.
 *
 * @param int $rid
 *   The id of the redirect to be loaded.
 * @param bool $reset
 *   Whether to reset the internal cache for the requested entity type.
 *
 * @return mixed
 *   Returns loaded redirect or FALSE if not found.
 */
function sanbi_redirect_load($rid, $reset = FALSE) {
  $redirects = entity_load('sanbi_redirect', array($rid), array(), $reset);
  return !empty($redirects) ? reset($redirects) : FALSE;
}

/**
 * Loads redirects and returns them ordered by weight.
 *
 * @param array $rids
 *   Array of redirect ids to be loaded.
 * @param array $conditions
 *   An associative array of conditions on the base table, where the keys are
 *   the database fields and the values are the values those fields must have.
 *   Instead, it is preferable to use EntityFieldQuery to retrieve a list of
 *   entity IDs loadable by this function.
 * @param bool $reset
 *   Whether to reset the internal cache for the requested entity type.
 *
 * @return array
 *   Returns loaded redirects array or empty array if none found.
 */
function sanbi_redirect_load_multiple($rids = array(), array $conditions = array(), $reset = FALSE) {
  // Order by weight.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'sanbi_redirect');
  // Get only provided rids but exclude if $rids array is empty.
  if (!empty($rids)) {
    $query->propertyCondition('rid', $rids, 'IN');
  }
  $query->propertyOrderBy('weight');
  $result = $query->execute();
  // Check for result and substitute reordered rids.
  if (isset($result['sanbi_redirect']) && !empty($result['sanbi_redirect'])) {
    $rids = array_keys($result['sanbi_redirect']);
  }
  return entity_load('sanbi_redirect', $rids, $conditions, $reset);
}
