<?php
/**
 * @file
 * views_plant_of_the_week_searches.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function views_plant_of_the_week_searches_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['views-9cf9bcc364c46efb916208aee9e14b4f'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9cf9bcc364c46efb916208aee9e14b4f',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -27,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -14,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-a60ac21bd5cfd0e7d9674857a9f70973'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'a60ac21bd5cfd0e7d9674857a9f70973',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -26,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -13,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-a79c3a7ac1262449c1167b0f676123c1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'a79c3a7ac1262449c1167b0f676123c1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -20,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -12,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_SA_distros'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_SA_distros',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -23,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -11,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_exposure'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_exposure',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -29,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_flower_colour'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_flower_colour',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -28,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -15,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_hort_zone'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_hort_zone',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -25,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_plant_type'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_plant_type',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -24,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => -16,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_soil_ph'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_soil_ph',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -22,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pow_search-facet_soil_type'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pow_search-facet_soil_type',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'plants/search/*',
    'roles' => array(),
    'themes' => array(
      'greenbox' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'greenbox',
        'weight' => -21,
      ),
      'tmp' => array(
        'region' => 'highlighted',
        'status' => 1,
        'theme' => 'tmp',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  return $export;
}
